### ISSUE TITLE
PyShExC allows illegal tripleExprLabel construct

### ISSUE THREAD

**Issue by hsolbrig** [shexSpec/grammar#12]
PyShExC allows the following construct:
```
<S> ( ( $<S_t> ( <a> . ;) )
```
But, because there is no place to record the id, the `S_t` label gets dropped.  Either this needs to be disallowed or a synthetic construct needs to be wrapped around the inner triple expressions (perhaps `EachOf`, although I believe that we have to allow fewer than 2 elements). 

The `EachOf` solution would be good because some of the code generators have had to do something kludgy like `<S> ( ( $<S_t> ( <dummy> .?); ...)` when there are no triples in `<S>` besides those in the elipses.

**Comment by ericprud** [comment]
If I balance the parens and change the outer ones to {}s, I get:
``` shex
<S> { ( $<S_t> ( <a> . ;) ) }
```
, which I believe looks like this in JSON:
``` json
{ "type": "Schema",
  "shapes": [
    { "type": "Shape",
      "id": "S",
      "expression": {
        "id": "/S_t",
        "type": "TripleConstraint",
        "predicate": "a"
      } } ],
  "@context": "http://www.w3.org/ns/shex.jsonld"
}
```
This seems consistent with the JSG:
```
TripleConstraint { id:tripleExprLabel? inverse:BOOL? predicate:IRIREF valueExpr:shapeExpr?
                   min:INTEGER? max:INTEGER? semActs:[SemAct+]? annotations:[Annotation+]? }
```

**Comment by hsolbrig** [comment]
Thanks -- will update the parser to handle this situation.  Should we get this in as a unit test?

**Comment by ericprud** [comment]
It currently tests to make sure TEs can have ids, e.g. [2EachInclude1](http://shex.io/shexTest/master/viewer.html?schemas#2EachInclude1) so I guess what's missing is the same but with some ()s. Can you confirm?

**Comment by hsolbrig** [comment]
Having trouble reproducing this -- will update the PyShEx interpreter to detect this situation, and will close this issue until (if) it re-appears.
