### ISSUE TITLE
[Question] Example 91 Validating RDF Data Book

### ISSUE THREAD

**Issue by mistermboy** [shexSpec/grammar#15]
This is a simplification of the example 91 of the [Validating RDF Data book](https://book.validatingrdf.com/bookHtml010.html) :
```
:TeacherAfter EXTRA a {
 :teaches    { a [:Course] } @:Course
}
```
I am wondering if the '@:Course' is correct because I was looking at the grammars and I think there is none that allows writing a 'shapeRef' after an 'inlineShapeExpression'

```
[43] unaryTripleExpr ::=('$' tripleExprLabel)? (tripleConstraint|bracketedTripleExpr) 
                        | include

[44] bracketedTripleExpr ::= 
     '(' tripleExpression ')' cardinality? annotation* semanticActions

[45] tripleConstraint ::= 
senseFlags? predicate inlineShapeExpression cardinality? annotation* semanticActions

[57] include ::= '&' tripleExprLabel
```

[Master   branch grammar](https://github.com/shexSpec/grammar/blob/master/bnf) 
[Shex2.1 branch grammar](https://github.com/shexSpec/grammar/blob/shex2.1/bnf)
[Shex.io grammar](http://shex.io/shex-semantics/#shexc)

**Comment by mistermboy** [comment]
Moved to https://github.com/shexSpec/shex/issues/100

**Comment by ericprud** [comment]
Agreed. should be
```
:TeacherAfter EXTRA a {
 :teaches    { a [:Course] } AND @:Course
}
```
Want to move (again) to https://github.com/labra/validatingRDFBookExamples ?

**Comment by mistermboy** [comment]
@ericprud Do you think I should move that kind of questions to https://github.com/labra/validatingRDFBookExamples?

I wrote them at https://github.com/shexSpec/shex/ to make them more visible, but I can move them if you think it's not a good place

**Comment by ericprud** [comment]
I'm not sure there's a generalization to be made but I think this specific issue is pretty uncontroversially a prob with the manuscript and not the language
